name: Get GitHub recent activities

on:
  schedule:
    # Runs every hour
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Get recent activities in gh

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: brandonwie/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET}}
